// ***********************************************************************
// ⚡ MvvmGen => https://github.com/thomasclaudiushuber/mvvmgen
// Copyright © by Thomas Claudius Huber
// Licensed under the MIT license => See the LICENSE file in project root
// ***********************************************************************

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using MvvmGen.SourceGenerator;
using System.ComponentModel;
using System.Reflection;
using Xunit;

namespace MvvmGen.Generator
{
  public class ViewModelSourceGeneratorTests
  {
    private static void ShouldGenerateExpectedCode(string inputCode, string expectedGeneratedCode)
    {
      var inputCompilation = CreateCompilation(inputCode);

      ViewModelSourceGenerator generator = new();

      GeneratorDriver driver = CSharpGeneratorDriver.Create(generator);

      driver = driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var outputCompilation, out var diagnostics);

      var runResult = driver.GetRunResult();

      Assert.Single(runResult.GeneratedTrees);
      Assert.True(runResult.Diagnostics.IsEmpty);

      var generatorResult = runResult.Results[0];
      Assert.Equal(generator, generatorResult.Generator);
      Assert.True(generatorResult.Diagnostics.IsEmpty);
      Assert.Single(generatorResult.GeneratedSources);
      Assert.Null(generatorResult.Exception);

      Assert.Equal(expectedGeneratedCode, generatorResult.GeneratedSources[0].SourceText.ToString());
    }

    private static Compilation CreateCompilation(string source)
            => CSharpCompilation.Create("compilation",
                new[] { CSharpSyntaxTree.ParseText(source) },
                new[] {
                  MetadataReference.CreateFromFile(typeof(Binder).GetTypeInfo().Assembly.Location),
                  MetadataReference.CreateFromFile(typeof(INotifyPropertyChanged).GetTypeInfo().Assembly.Location),
                  MetadataReference.CreateFromFile(typeof(ViewModelAttribute).GetTypeInfo().Assembly.Location)},
                new CSharpCompilationOptions(OutputKind.ConsoleApplication));


    private static string AutoGeneratedComment => $@"// <auto-generated>
//   This code was generated for you by
//   ⚡ MvvmGen => https://github.com/thomasclaudiushuber/mvvmgen
//   Generator version: { typeof(ViewModelSourceGenerator).Assembly.GetName().Version?.ToString(3) }
// </auto-generated>";

    private static string AutoGeneratedUsings => $@"using System.ComponentModel;
using MvvmGen.Commands;
using MvvmGen.ViewModels;";

    [Fact]
    public void GenerateViewModelWithFullQualifiedAttributeName()
    {
      ShouldGenerateExpectedCode(
@"namespace MyCode
{   
  [MvvmGen.ViewModel]
  public partial class EmployeeViewModel
  {
  }
}",
$@"{AutoGeneratedComment}
{AutoGeneratedUsings}

namespace MyCode
{{
  partial class EmployeeViewModel : ViewModelBase
  {{
    public void Initialize()
    {{
    }}
  }}
}}
");
    }

    [Fact]
    public void GenerateViewModelBase()
    {
      ShouldGenerateExpectedCode(
@"using MvvmGen;

namespace MyCode
{   
  [ViewModel]
  public partial class EmployeeViewModel
  {
  }
}",
$@"{AutoGeneratedComment}
{AutoGeneratedUsings}

namespace MyCode
{{
  partial class EmployeeViewModel : ViewModelBase
  {{
    public void Initialize()
    {{
    }}
  }}
}}
");
    }

    [Fact]
    public void GenerateViewModelBaseNotIfClassInheritsFromOtherClass()
    {
      ShouldGenerateExpectedCode(
 @"using System.ComponentModel;
using MvvmGen;

namespace MyCode
{   
  public class CustomViewModelBase
  {
    protected void OnPropertyChanged(string propertyName) { }
  }

  [ViewModel]
  public partial class EmployeeViewModel : CustomViewModelBase
  {
  }
}",
 $@"{AutoGeneratedComment}
{AutoGeneratedUsings}

namespace MyCode
{{
  partial class EmployeeViewModel
  {{
    public void Initialize()
    {{
    }}
  }}
}}
");
    }

    [InlineData("firstName")]
    [InlineData("_firstName")]
    [InlineData("m_firstName")]
    [Theory]
    public void GenerateProperty(string fieldName)
    {
      ShouldGenerateExpectedCode(
$@"using MvvmGen;

namespace MyCode
{{   
  [ViewModel]
  public partial class EmployeeViewModel
  {{
    [Property] private string {fieldName};
  }}
}}",
$@"{AutoGeneratedComment}
{AutoGeneratedUsings}

namespace MyCode
{{
  partial class EmployeeViewModel : ViewModelBase
  {{
    public void Initialize()
    {{
    }}
    public string FirstName
    {{
      get => {fieldName};
      set
      {{
        if ({fieldName} != value)
        {{
          {fieldName} = value;
          OnPropertyChanged(""FirstName"");
        }}
      }}
    }}
  }}
}}
");
    }

    [InlineData("PropertyName=\"AmazingFirstName\"", "AmazingFirstName")]
    [InlineData("\"IncredibleFirstName\"", "IncredibleFirstName")]
    [Theory]
    public void GeneratePropertyWithName(string attributeArgument, string expectedPropertyName)
    {
      ShouldGenerateExpectedCode(
$@"using MvvmGen;

namespace MyCode
{{   
  [ViewModel]
  public partial class EmployeeViewModel
  {{
    [Property({attributeArgument})] private string _firstName;
  }}
}}",
$@"{AutoGeneratedComment}
{AutoGeneratedUsings}

namespace MyCode
{{
  partial class EmployeeViewModel : ViewModelBase
  {{
    public void Initialize()
    {{
    }}
    public string {expectedPropertyName}
    {{
      get => _firstName;
      set
      {{
        if (_firstName != value)
        {{
          _firstName = value;
          OnPropertyChanged(""{expectedPropertyName}"");
        }}
      }}
    }}
  }}
}}
");
    }


    [Fact]
    public void GenerateCommandProperty()
    {
      ShouldGenerateExpectedCode(
@"using MvvmGen;

namespace MyCode
{   
  [ViewModel]
  public partial class EmployeeViewModel
  {
    [Command]public void SaveAll() { }
  }
}",
$@"{AutoGeneratedComment}
{AutoGeneratedUsings}

namespace MyCode
{{
  partial class EmployeeViewModel : ViewModelBase
  {{
    public void Initialize()
    {{
      SaveAllCommand = new(SaveAll);
    }}

    public DelegateCommand SaveAllCommand {{ get; private set; }}
  }}
}}
");
    }

    [Fact]
    public void GenerateCommandPropertyWithCanExecuteMethod()
    {
      ShouldGenerateExpectedCode(
@"using MvvmGen;

namespace MyCode
{   
  [ViewModel]
  public partial class EmployeeViewModel
  {
    [Command(nameof(CanSaveAll))]
    public void SaveAll() { }

    public bool CanSaveAll() => true;
  }
}",
$@"{AutoGeneratedComment}
{AutoGeneratedUsings}

namespace MyCode
{{
  partial class EmployeeViewModel : ViewModelBase
  {{
    public void Initialize()
    {{
      SaveAllCommand = new(SaveAll, CanSaveAll);
    }}

    public DelegateCommand SaveAllCommand {{ get; private set; }}
  }}
}}
");
    }

    [Fact]
    public void GenerateCommandPropertyWithCanExecuteMethodUsingNamedArgument()
    {
      ShouldGenerateExpectedCode(
@"using MvvmGen;

namespace MyCode
{   
  [ViewModel]
  public partial class EmployeeViewModel
  {
    [Command(CanExecuteMethod=nameof(CanSaveAll))]
    public void SaveAll() { }

    public bool CanSaveAll() => true;
  }
}",
$@"{AutoGeneratedComment}
{AutoGeneratedUsings}

namespace MyCode
{{
  partial class EmployeeViewModel : ViewModelBase
  {{
    public void Initialize()
    {{
      SaveAllCommand = new(SaveAll, CanSaveAll);
    }}

    public DelegateCommand SaveAllCommand {{ get; private set; }}
  }}
}}
");
    }

    [InlineData("CanExecuteMethod=nameof(CanSaveAll)")]
    [InlineData("nameof(CanSaveAll)")]
    [Theory]
    public void GenerateCommandPropertyWithCanExecuteMethodAndCommandNameUsingNamedArgument(string canExecuteParameter)
    {
      ShouldGenerateExpectedCode(
$@"using MvvmGen;

namespace MyCode
{{   
  [ViewModel]
  public partial class EmployeeViewModel
  {{
    [Command({canExecuteParameter}, CommandName=""SuperCommand"")]
    public void SaveAll() {{ }}

    public bool CanSaveAll() => true;
  }}
}}",
$@"{AutoGeneratedComment}
{AutoGeneratedUsings}

namespace MyCode
{{
  partial class EmployeeViewModel : ViewModelBase
  {{
    public void Initialize()
    {{
      SuperCommand = new(SaveAll, CanSaveAll);
    }}

    public DelegateCommand SuperCommand {{ get; private set; }}
  }}
}}
");
    }
  }
}
