// ***********************************************************************
// ⚡ MvvmGen => https://github.com/thomasclaudiushuber/mvvmgen
// Copyright © by Thomas Claudius Huber
// Licensed under the MIT license => See the LICENSE file in project root
// ***********************************************************************

using Xunit;

namespace MvvmGen.SourceGenerators
{
    public class CreateViewModelFactoryAttributeTests : ViewModelGeneratorTestsBase
    {
        [InlineData("public", "public")]
        [InlineData("internal", "internal")]
        [InlineData("internal", "")]
        [Theory]
        public void GenerateFactoryClassForViewModel(string expectedAccessModifierFactory, string accessModifierViewModel)
        {
            ShouldGenerateExpectedCode(
      $@"using MvvmGen;

namespace MyCode
{{   
  public interface IEmployeeDataProvider {{}}

  [Inject(typeof(IEmployeeDataProvider)))]
  [GenerateViewModelFactory]
  [ViewModel]
  {accessModifierViewModel} partial class EmployeeViewModel
  {{
  }}
}}",
      $@"{AutoGeneratedComment}
{AutoGeneratedUsings}

namespace MyCode
{{
    partial class EmployeeViewModel : ViewModelBase
    {{
        public EmployeeViewModel(MyCode.IEmployeeDataProvider employeeDataProvider)
        {{
            this.EmployeeDataProvider = employeeDataProvider;
            this.OnInitialize();
        }}

        partial void OnInitialize();

        protected MyCode.IEmployeeDataProvider EmployeeDataProvider {{ get; private set; }}
    }}

    {expectedAccessModifierFactory} interface IEmployeeViewModelFactory : IViewModelFactory<EmployeeViewModel> {{ }}

    {expectedAccessModifierFactory} class EmployeeViewModelFactory : IEmployeeViewModelFactory
    {{
        public EmployeeViewModelFactory(MyCode.IEmployeeDataProvider employeeDataProvider)
        {{
            this.EmployeeDataProvider = employeeDataProvider;
        }}

        protected MyCode.IEmployeeDataProvider EmployeeDataProvider {{ get; private set; }}

        public EmployeeViewModel Create() => new EmployeeViewModel(EmployeeDataProvider);
    }}
}}
");
        }
    }
}
