// ***********************************************************************
// ⚡ MvvmGen => https://github.com/thomasclaudiushuber/mvvmgen
// Copyright © by Thomas Claudius Huber
// Licensed under the MIT license => See LICENSE file in repository root
// ***********************************************************************

using Xunit;

namespace MvvmGen.SourceGenerators
{
    public partial class PropertyAttributeTests : ViewModelGeneratorTestsBase
    {
        [InlineData("firstName")]
        [InlineData("_firstName")]
        [InlineData("m_firstName")]
        [Theory]
        public void GenerateProperty(string fieldName)
        {
            ShouldGenerateExpectedCode(
      $@"using MvvmGen;

namespace MyCode
{{
  [ViewModel]
  public partial class EmployeeViewModel
  {{
    [Property] private string {fieldName};
  }}
}}",
      $@"{AutoGeneratedTopContent}

namespace MyCode
{{
    partial class EmployeeViewModel : global::MvvmGen.ViewModels.ViewModelBase
    {{
        public EmployeeViewModel()
        {{
            this.OnInitialize();
        }}

        partial void OnInitialize();

        public string FirstName
        {{
            get => {fieldName};
            set
            {{
                if ({fieldName} != value)
                {{
                    {fieldName} = value;
                    OnPropertyChanged(""FirstName"");
                }}
            }}
        }}
    }}
}}
");
        }

        [InlineData("public")]
        [InlineData("private")]
        [InlineData("protected")]
        [InlineData("protected internal")]
        [InlineData("internal")]
        [Theory]
        public void GeneratePartialProperty(string accessModifier)
        {
            string propertyName = "FirstName";
            string fieldName = "_firstName";
            ShouldGenerateExpectedCode(
      $@"using MvvmGen;

namespace MyCode
{{
  [ViewModel]
  public partial class EmployeeViewModel
  {{
    [Property] {accessModifier} partial string? {propertyName} {{ get; set; }}
  }}
}}",
      $@"{AutoGeneratedTopContent}

namespace MyCode
{{
    partial class EmployeeViewModel : global::MvvmGen.ViewModels.ViewModelBase
    {{
        public EmployeeViewModel()
        {{
            this.OnInitialize();
        }}

        partial void OnInitialize();

        private string? _firstName;

        {accessModifier} partial string? FirstName
        {{
            get => {fieldName};
            set
            {{
                if ({fieldName} != value)
                {{
                    {fieldName} = value;
                    OnPropertyChanged(""FirstName"");
                }}
            }}
        }}
    }}
}}
");
        }

        [InlineData("PropertyName=\"AmazingFirstName\"", "AmazingFirstName")]
        [InlineData("\"IncredibleFirstName\"", "IncredibleFirstName")]
        [Theory]
        public void GeneratePropertyWithName(string attributeArgument, string expectedPropertyName)
        {
            ShouldGenerateExpectedCode(
      $@"using MvvmGen;

namespace MyCode
{{
  [ViewModel]
  public partial class EmployeeViewModel
  {{
    [Property({attributeArgument})] private string _firstName;
  }}
}}",
      $@"{AutoGeneratedTopContent}

namespace MyCode
{{
    partial class EmployeeViewModel : global::MvvmGen.ViewModels.ViewModelBase
    {{
        public EmployeeViewModel()
        {{
            this.OnInitialize();
        }}

        partial void OnInitialize();

        public string {expectedPropertyName}
        {{
            get => _firstName;
            set
            {{
                if (_firstName != value)
                {{
                    _firstName = value;
                    OnPropertyChanged(""{expectedPropertyName}"");
                }}
            }}
        }}
    }}
}}
");
        }
    }
}
