// ***********************************************************************
// ⚡ MvvmGen => https://github.com/thomasclaudiushuber/mvvmgen
// Copyright © by Thomas Claudius Huber
// Licensed under the MIT license => See the LICENSE file in project root
// ***********************************************************************

using Xunit;

namespace MvvmGen.SourceGenerators
{
    public class PropertyCallMethodAttributeTests : ViewModelGeneratorTestsBase
    {
        [InlineData("MyMethod();","", "[PropertyCallMethod(nameof(MyMethod))]")]
        [InlineData("MyMethod();","", "[PropertyCallMethod(\"MyMethod\")]")]
        [InlineData("MyMethod(_selectedItem);","string item", "[PropertyCallMethod(nameof(MyMethod),MethodArgs=\"_selectedItem\")]")]
        [Theory]
        public void GenerateMethodCallInProperty(string expectedMethodCall, string methodParameters, string onChangeCallMethodAttribute)
        {
            ShouldGenerateExpectedCode(
      $@"using MvvmGen;
using MvvmGen.Events;

namespace MyCode
{{   
  [ViewModel(GenerateConstructor=false)]
  public partial class EmployeeViewModel
  {{
    private void MyMethod({methodParameters}){{ }}

    {onChangeCallMethodAttribute}
    [Property] 
    private string _selectedItem;
  }}
}}",
      $@"{AutoGeneratedComment}
{AutoGeneratedUsings}

namespace MyCode
{{
    partial class EmployeeViewModel : ViewModelBase
    {{
        public string SelectedItem
        {{
            get => _selectedItem;
            set
            {{
                if (_selectedItem != value)
                {{
                    _selectedItem = value;
                    OnPropertyChanged(""SelectedItem"");
                    {expectedMethodCall}
                }}
            }}
        }}
    }}
}}
");
        }
    }

}

