// ***********************************************************************
// ⚡ MvvmGen => https://github.com/thomasclaudiushuber/mvvmgen
// Copyright © by Thomas Claudius Huber
// Licensed under the MIT license => See LICENSE file in repository root
// ***********************************************************************

using Xunit;

namespace MvvmGen.SourceGenerators
{
    public partial class ViewModelAttributeTests : ViewModelGeneratorTestsBase
    {
        [InlineData("[MvvmGen.ViewModel]")]
        [InlineData("[ViewModel]")]
        [Theory]
        public void GenerateViewModel(string attribute)
        {
            ShouldGenerateExpectedCode(
      $@"using MvvmGen;

namespace MyCode
{{
  {attribute}
  public partial class EmployeeViewModel
  {{
  }}
}}",
      $@"{AutoGeneratedTopContent}

namespace MyCode
{{
    partial class EmployeeViewModel : global::MvvmGen.ViewModels.ViewModelBase
    {{
        public EmployeeViewModel()
        {{
            this.OnInitialize();
        }}

        partial void OnInitialize();
    }}
}}
");
        }

        [Fact]
        public void GenerateViewModelWithoutConstructor()
        {
            ShouldGenerateExpectedCode(
      $@"using MvvmGen;

namespace MyCode
{{
  [ViewModel(GenerateConstructor=false)]
  public partial class EmployeeViewModel
  {{
  }}
}}",
      $@"{AutoGeneratedTopContent}

namespace MyCode
{{
    partial class EmployeeViewModel : global::MvvmGen.ViewModels.ViewModelBase
    {{
    }}
}}
");
        }

        [Fact]
        public void GenerateViewModelWithoutConstructorNoEmptyLineForFirstMember()
        {
            ShouldGenerateExpectedCode(
      $@"using MvvmGen;

namespace MyCode
{{
  [Inject(typeof(string),""InjectedString"")]
  [ViewModel(GenerateConstructor=false)]
  public partial class EmployeeViewModel
  {{
  }}
}}",
      $@"{AutoGeneratedTopContent}

namespace MyCode
{{
    partial class EmployeeViewModel : global::MvvmGen.ViewModels.ViewModelBase
    {{
        protected string InjectedString {{ get; private set; }}
    }}
}}
");
        }

        [Fact]
        public void GenerateViewModelBaseNotIfClassIndirectlyInheritsFromIt()
        {
            ShouldGenerateExpectedCode(
       @"using System.ComponentModel;
using MvvmGen;
using MvvmGen.ViewModels;

namespace MyCode
{
  public class CustomViewModelBase : global::MvvmGen.ViewModels.ViewModelBase
  {
    protected void OnPropertyChanged(string propertyName) { }
  }

  [ViewModel]
  public partial class EmployeeViewModel : CustomViewModelBase
  {
  }
}",
       $@"{AutoGeneratedTopContent}

namespace MyCode
{{
    partial class EmployeeViewModel
    {{
        public EmployeeViewModel()
        {{
            this.OnInitialize();
        }}

        partial void OnInitialize();
    }}
}}
");
        }

        [Fact]
        public void GenerateViewModelBaseNotIfClassIndirectlyInheritsFromItViewAnotherViewModelAttribute()
        {
            ShouldGenerateExpectedCode(
       @"using System.ComponentModel;
using MvvmGen;
using MvvmGen.ViewModels;

namespace MyCode
{
  [ViewModel]
  public class CustomViewModelBase
  {
  }

  [ViewModel]
  public partial class EmployeeViewModel : CustomViewModelBase
  {
  }
}",
         $@"{AutoGeneratedTopContent}

namespace MyCode
{{
    partial class CustomViewModelBase : global::MvvmGen.ViewModels.ViewModelBase
    {{
        public CustomViewModelBase()
        {{
            this.OnInitialize();
        }}

        partial void OnInitialize();
    }}
}}
",
       $@"{AutoGeneratedTopContent}

namespace MyCode
{{
    partial class EmployeeViewModel
    {{
        public EmployeeViewModel()
        {{
            this.OnInitialize();
        }}

        partial void OnInitialize();
    }}
}}
");
        }

        [Fact]
        public void GenerateViewModelBaseNotIfClassIndirectlyInheritsFromItViewAnotherViewModelAttributeWithMoreLevels()
        {
            ShouldGenerateExpectedCode(
       $@"using System.ComponentModel;
using MvvmGen;
using MvvmGen.ViewModels;

namespace MyCode
{{
  [ViewModel]
  public class MoreCustomViewModelBase
  {{
  }}

  [ViewModel]
  public class CustomViewModelBase : MoreCustomViewModelBase
  {{
  }}

  [ViewModel]
  public partial class EmployeeViewModel : CustomViewModelBase
  {{
  }}
}}",
          $@"{AutoGeneratedTopContent}

namespace MyCode
{{
    partial class MoreCustomViewModelBase : global::MvvmGen.ViewModels.ViewModelBase
    {{
        public MoreCustomViewModelBase()
        {{
            this.OnInitialize();
        }}

        partial void OnInitialize();
    }}
}}
", $@"{AutoGeneratedTopContent}

namespace MyCode
{{
    partial class CustomViewModelBase
    {{
        public CustomViewModelBase()
        {{
            this.OnInitialize();
        }}

        partial void OnInitialize();
    }}
}}
",
       $@"{AutoGeneratedTopContent}

namespace MyCode
{{
    partial class EmployeeViewModel
    {{
        public EmployeeViewModel()
        {{
            this.OnInitialize();
        }}

        partial void OnInitialize();
    }}
}}
");
        }

        [Fact]
        public void GenerateViewModelBaseNotIfClassIndirectlyInheritsFromItViewAnotherViewModelAttributeWithMoreLevelsAndWithoutViewModelAttributeOnMiddleClass()
        {
            ShouldGenerateExpectedCode(
       $@"using System.ComponentModel;
using MvvmGen;
using MvvmGen.ViewModels;

namespace MyCode
{{
  [ViewModel]
  public class MoreCustomViewModelBase
  {{
  }}

  // [ViewModel]
  public class CustomViewModelBase : MoreCustomViewModelBase
  {{
  }}

  [ViewModel]
  public partial class EmployeeViewModel : CustomViewModelBase
  {{
  }}
}}",
          $@"{AutoGeneratedTopContent}

namespace MyCode
{{
    partial class MoreCustomViewModelBase : global::MvvmGen.ViewModels.ViewModelBase
    {{
        public MoreCustomViewModelBase()
        {{
            this.OnInitialize();
        }}

        partial void OnInitialize();
    }}
}}
",
       $@"{AutoGeneratedTopContent}

namespace MyCode
{{
    partial class EmployeeViewModel
    {{
        public EmployeeViewModel()
        {{
            this.OnInitialize();
        }}

        partial void OnInitialize();
    }}
}}
");
        }
    }
}
