// ***********************************************************************
// ⚡ MvvmGen => https://github.com/thomasclaudiushuber/mvvmgen
// Copyright © by Thomas Claudius Huber
// Licensed under the MIT license => See the LICENSE file in project root
// ***********************************************************************

using System;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace MvvmGen.SourceGenerators
{
    public class ViewModelGeneratorTestsBase
    {
        protected static void ShouldGenerateExpectedCode(string inputCode, params string[] expectedGeneratedCode)
        {
            var metadataReferences = AppDomain.CurrentDomain.GetAssemblies().Where(a => !a.IsDynamic).Select(a => MetadataReference.CreateFromFile(a.Location)).ToList();
            var inputCompilation = CreateCompilation(inputCode, metadataReferences.ToArray());

            ViewModelGenerator generator = new();

            GeneratorDriver driver = CSharpGeneratorDriver.Create(generator);

            driver = driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var outputCompilation, out var diagnostics);

            var runResult = driver.GetRunResult();

            Assert.Equal(expectedGeneratedCode.Length, runResult.GeneratedTrees.Length);
            Assert.True(runResult.Diagnostics.IsEmpty);

            var generatorResult = runResult.Results[0];
            Assert.Equal(generator, generatorResult.Generator);
            Assert.True(generatorResult.Diagnostics.IsEmpty);
            Assert.Equal(expectedGeneratedCode.Length, generatorResult.GeneratedSources.Length);
            Assert.Null(generatorResult.Exception);

            for (int i = 0; i < expectedGeneratedCode.Length; i++)
            {
                Assert.Equal(expectedGeneratedCode[i], generatorResult.GeneratedSources[i].SourceText.ToString());
            }
        }

        protected static Compilation CreateCompilation(string source, MetadataReference[] metadataReferences)
                => CSharpCompilation.Create("compilation",
                    new[] { CSharpSyntaxTree.ParseText(source) },
                    metadataReferences,
                    new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));


        protected static string AutoGeneratedComment => $@"// <auto-generated>
//   This code was generated for you by
//   ⚡ MvvmGen, a tool created by Thomas Claudius Huber (https://www.thomasclaudiushuber.com)
//   Generator version: { typeof(ViewModelGenerator).Assembly.GetName().Version?.ToString(3) }
// </auto-generated>";

        protected static string AutoGeneratedUsings => $@"using MvvmGen.Commands;
using MvvmGen.Events;
using MvvmGen.ViewModels;";
    }
}
